#!/bin/bash

SCRIPT_REPO="https://code.videolan.org/videolan/libbdplus.git"
SCRIPT_COMMIT="a05a91dca4bc468e74ebb779e8ff1650ac2ba556"

ffbuild_depends() {
    echo libgpg-error
    echo libgcrypt
}

ffbuild_enabled() {
    return 0
}

ffbuild_dockerdl() {
    default_dl .
}

ffbuild_dockerbuild() {
    set -e

    ./bootstrap || return 1

    local DEP_LIBS="-lgcrypt -lgpg-error"

    local myconf=(
        --prefix="$FFBUILD_PREFIX"
        --libdir="${FFBUILD_PREFIX}/lib"
        --host="$FFBUILD_TOOLCHAIN"
        --with-pic
        --disable-doc
        --with-libgcrypt-prefix="$FFBUILD_PREFIX"
        --with-gpg-error-prefix="$FFBUILD_PREFIX"
        # --without-libaacs
    )

    [[ "${PREFER_SHARED}" == "1" ]] && \
        myconf+=( --disable-static --enable-shared ) || \
        myconf+=( --enable-static --disable-shared )

    CFLAGS="$CFLAGS ${USELTO:-}${USELTO_C:-}" \
    CPPFLAGS="$CPPFLAGS" \
    CXXFLAGS="$CXXFLAGS ${USELTO:-}${USELTO_C:-}" \
    LDFLAGS="$LDFLAGS ${USELTO:-}${USELTO_L:-}" \
    LIBS="$DEP_LIBS $LIBS" \
    ./configure "${myconf[@]}" || return 1

    make -j$(nproc) $MAKE_V || return 1
    make install DESTDIR="$FFBUILD_DESTDIR" || return 1

    local PC_FILE="$PC_DIR/libbdplus.pc"

    if [[ ! -f "$PC_FILE" ]]; then
        log_error "Critical Error: libbdplus.pc was not generated by build system."
    fi
    sed -i "s|^prefix=.*|prefix=${FFBUILD_PREFIX}|" "$PC_FILE"
    if [[ $TARGET == win64 ]]; then
        if ! grep -qF -- "-lws2_32" "$PC_FILE"; then
            sed -i "/^Libs:/ s/$/ -lws2_32/" "$PC_FILE"
        fi
    fi
    if ! grep -qF -- "-lstdc++" "$PC_FILE"; then
        echo "Libs.private: -lstdc++" >> "$PC_FILE"
    fi
}
