#!/bin/bash

SCRIPT_REPO="https://code.videolan.org/videolan/libaacs.git"
SCRIPT_COMMIT="bf52e06197a715581a477c5cf265fa80fe5b25e7"

ffbuild_depends() {
    echo libgpg-error
    echo libgcrypt
}

ffbuild_enabled() {
    return 1
}

ffbuild_dockerdl() {
    default_dl .
}

ffbuild_dockerbuild() {
    set -e

    if [[ -f "Makefile.am" ]]; then
        sed -i "s|AM_CFLAGS = -std=c99 \$(LIBGCRYPT_CFLAGS) \$(GPG_ERROR_CFLAGS)|AM_CFLAGS = -std=c99 \$(LIBGCRYPT_CFLAGS) \$(GPG_ERROR_CFLAGS) -Wno-trigraphs|g" "Makefile.am"
    fi

    if [[ -f "src/file/keydb.c" && -f "src/Makefile.am" ]]; then
        if ! grep -qF "src/file/keydb.c" "src/Makefile.am"; then
            sed -i "/src\/file\/keydbcfg.h \\\\/a \\\tsrc/file/keydb.c \\\\" "src/Makefile.am"
        fi
    fi

    # Disable compilation and installation of aacs_info.exe
    log_info "Disabling aacs_info compilation and installation..."
    if [[ -f "Makefile.am" ]]; then
        # Move aacs_info from installed (bin_PROGRAMS) to test/non-installable (noinst_PROGRAMS)
        sed -i 's/bin_PROGRAMS = aacs_info/noinst_PROGRAMS += aacs_info/g' Makefile.am
    fi

    ./bootstrap || return 1

    local DEP_LIBS="-lgcrypt -lgpg-error"

    local myconf=(
        --prefix="$FFBUILD_PREFIX"
        --libdir="${FFBUILD_PREFIX}/lib"
        --host="$FFBUILD_TOOLCHAIN"
        --with-pic
    )

    [[ "${PREFER_SHARED}" == "1" ]] && \
        myconf+=( --disable-static --enable-shared ) || \
        myconf+=( --enable-static --disable-shared )

    CFLAGS="$CFLAGS ${USELTO:-}${USELTO_C:-}" \
    CPPFLAGS="$CPPFLAGS" \
    CXXFLAGS="$CXXFLAGS ${USELTO:-}${USELTO_C:-}" \
    LDFLAGS="$LDFLAGS ${USELTO:-}${USELTO_L:-}" \
    LIBS="$DEP_LIBS $LIBS" \
    ./configure "${myconf[@]}" || return 1

    make -j$(nproc) $MAKE_V || return 1
    make install DESTDIR="$FFBUILD_DESTDIR" || return 1

    local PC_FILE="$PC_DIR/libaacs.pc"

    if [[ ! -f "$PC_FILE" ]]; then
        log_error "Critical Error: libaacs.pc was not generated by VideoLAN autotools build suite."
    fi
    sed -i "s|^prefix=.*|prefix=${FFBUILD_PREFIX}|" "$PC_FILE"
    if [[ $TARGET == win64 ]]; then
        if ! grep -qF -- "-lws2_32" "$PC_FILE"; then
            sed -i "/^Libs:/ s/$/ -lws2_32/" "$PC_FILE"
        fi
    fi
    if ! grep -qF -- "-lstdc++" "$PC_FILE"; then
        sed -i "/^Libs.private:/ s/$/ -lstdc++/" "$PC_FILE"
    fi
    sed -i "s|^Cflags:.*|& -I\${includedir}/libaacs|" "$PC_FILE"
}
