#!/bin/bash

SCRIPT_REPO="https://gitlab.freedesktop.org/freetype/freetype.git"
SCRIPT_COMMIT="5336c0d4da22a13dab3389eb153b12672fdf841c"

ffbuild_depends() {
    echo fontconfig
    echo zlib
    echo bzlib
    echo brotli
    echo libpng
    echo harfbuzz
}

ffbuild_enabled() {
    return 0
}

ffbuild_dockerdl() {
    default_dl .
    echo "git-mini-clone \"https://github.com/nyorain/dlg.git\" \"master\" subprojects/dlg"
    echo "rm -rf docs/oldlogs"
}

ffbuild_dockerbuild() {
    set -e

    if [[ -f "subprojects/dlg/meson_options.txt" ]]; then
        log_info "Patching subprojects/dlg to always use color..."
        sed -i "s/option('default_output_always_color', type: 'boolean', value: false)/option('default_output_always_color', type: 'boolean', value: true)/" subprojects/dlg/meson_options.txt
    fi

    ./autogen.sh

    local myconf=(
        --prefix="$FFBUILD_PREFIX"
        --host="$FFBUILD_TOOLCHAIN"
        --with-pic
    )

    export static_flags=""
    [[ "${PREFER_SHARED}" != "1" ]] && static_flags="-DFT2_BUILD_LIBRARY"

    [[ "${PREFER_SHARED}" == "1" ]] && \
        myconf+=( --disable-static --enable-shared ) || \
        myconf+=( --enable-static --disable-shared )

    local ZLIB_LIBS=""
    local BZIP2_LIBS=""
    local PNG_LIBS=""
    local BROTLI_LIBS=""
    local HB_LIBS=""

    if has_library "z"; then
        log_info "ZLIB library detected. Building FreeType with ZLIB..."
        myconf+=( --with-zlib )
        local ZLIB_LIBS="-lz"
    else
        log_warn "ZLIB library not found. Building FreeType without ZLIB..."
        myconf+=( --without-zlib )
    fi
    if has_library "bz2"; then
        log_info "BZIP2 library detected. Building FreeType with Bzip2..."
        myconf+=( --with-bzip2 )
        local BZIP2_LIBS="-lbz2"
    else
        log_warn "BZIP2 library not found. Building FreeType without Bzip2..."
        myconf+=( --without-bzip2 )
    fi
    if has_library "png"; then
        log_info "PNG library detected. Building FreeType with PNG support..."
        myconf+=( --with-png )
        local PNG_LIBS="-lpng"
    else
        log_warn "PNG library not found. Building FreeType without PNG..."
        myconf+=( --without-png )
    fi
    if has_library "brotlidec"; then
        log_info "Brotli library detected. Building FreeType with Brotli support..."
        myconf+=( --with-brotli )
        local BROTLI_LIBS="-lbrotlienc -lbrotlidec -lbrotlicommon"
    else
        log_warn "Brotli library not found. Building FreeType without Brotli..."
        myconf+=( --without-brotli )
    fi
    if has_library "harfbuzz"; then
        log_info "HarfBuzz library detected. Building FreeType with HarfBuzz shaping support..."
        myconf+=( --with-harfbuzz )

        # Build the HarfBuzz/Cairo stack, if present.
        # If ICU (icudt) was built previously, also add harfbuzz-icu
        local HB_ICU=""
        if has_library "icudt"; then
            local HB_ICU="-lharfbuzz-icu"
        fi
        # HarfBuzz safe link list (including helper libs if generated by Meson)
        local HB_LIBS="${HB_ICU} -lharfbuzz-subset -lharfbuzz-cairo -lcairo-gobject -lcairo -lharfbuzz-vector -lharfbuzz-raster -lharfbuzz"
    else
        log_warn "HarfBuzz library not found. Building FreeType without HarfBuzz API..."
        myconf+=( --without-harfbuzz )
    fi

    local DEP_LIBS="-Wl,--start-group ${HB_LIBS} ${PNG_LIBS} ${BZIP2_LIBS} ${BROTLI_LIBS} ${ZLIB_LIBS} -Wl,--end-group"

    local WIN_LIBS="$LIBS"

    log_info "Configuring FreeType with Autotools..."

    CFLAGS="$CFLAGS ${USELTO}${USELTO_C}" \
    LDFLAGS="$LDFLAGS ${USELTO}${USELTO_L}" \
    CPPFLAGS="$CPPFLAGS $static_flags" \
    CXXFLAGS="$CXXFLAGS $static_flags ${USELTO}${USELTO_C}" \
    LIBS="$DEP_LIBS $WIN_LIBS" \
    ./configure "${myconf[@]}" || return 1

    make -j$(nproc) $MAKE_V || return 1
    make install DESTDIR="$FFBUILD_DESTDIR" || return 1

    for pc in "$PC_DIR"/{freetype,freetype2}.pc; do
        [[ -f "$pc" ]] || continue
        sed -i "s|^Cflags:.*|Cflags: -I\${includedir}/freetype2|" "$pc"
    done

    local PC_LINK="$PC_DIR/freetype.pc"
    ln -sf freetype2.pc "$PC_LINK"
}

ffbuild_configure() {
    echo --enable-libfreetype
}

ffbuild_unconfigure() {
    echo --disable-libfreetype
}